Building Responsive Websites
kiptubei/The-Next-Web pull request #4
Opened 2020-05-01 21:58 UTC by kiptubei

This project entails the replication of The next web which is is responsive as per the device the site is viewed on. The specifications include:

Small (-sm-) devices (landscape phones, 400px and up)
Medium (-md-) devices (tablets, 768px and up)
Normal Screens (-l-) devices (laptops/notebooks 1024 and up)
Extra large (-xl-) devices (large desktops, 1200px and up)

2020-05-04 12:06 UTC, santiago-rodrig commented
## Pull Request under review by @santiago-rodrig (TSE)

2020-05-04 12:52 UTC, santiago-dev96 requested changes
# Some requirements are not fulfilled

Good job so far! You've been working hard until now, but some requirements are not met.

### TWN logo should disappear on medium and small-sized devices

![image](https://user-images.githubusercontent.com/43162770/80967126-d773bb00-8de3-11ea-855e-9df44fcb342b.png)

---

### Categories section should have two category boxes per row on medium-sized devices

![image](https://user-images.githubusercontent.com/43162770/80967148-e5c1d700-8de3-11ea-963e-8d4495406346.png)

---

### The **Latest Funding** section is missing

![image](https://user-images.githubusercontent.com/43162770/80967258-0d18a400-8de4-11ea-8c3a-7d5517fcbe7b.png)

![image](https://user-images.githubusercontent.com/43162770/80967242-04c06900-8de4-11ea-9d71-3332e132ec40.png)

## Request for another code review

After implementing all the changes, please request another code review. Have a nice day!

2020-05-04 12:52 UTC, santiago-rodrig commented on stylesheets/style.css
> +  box-sizing: border-box;
You shouldn't have to declare the box-sizing if you already did that for all elements a few lines above.

2020-05-04 12:52 UTC, santiago-rodrig commented on stylesheets/style.css
> +  box-sizing: border-box;
Same here.

2020-05-04 12:52 UTC, santiago-rodrig commented on stylesheets/style.css
> +@media screen and (min-width: 400px) and (max-width: 768px) {
You should only have two breakpoints, 768px and above for medium devices and 1024px and above for large devices.

2020-05-04 12:52 UTC, santiago-rodrig commented on stylesheets/style.css
> +  .d-none-tablet {
Check this one, because the TWN logo is still showing up on small and medium devices.

2020-05-04 12:52 UTC, santiago-rodrig commented on stylesheets/style.css
> +    flex-direction: row;
Flex boxes by default have a row direction.

2020-05-06 06:35 UTC, mikenath223 approved these changes
### Hi @kiptubei  and @uimarshall 👋

You both did well on this project.👍

- [ ] OPTIONAL - Consider grouping elements with the same properties together. We want to follow the Don't Repeat Yourself(DRY) principle. CSS bad practices shouldn't used refer to this([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright).
[SCREENSHOT]👇
![ice_screenshot_20200506-072727](https://user-images.githubusercontent.com/33323077/81144360-c950a680-8f6b-11ea-8f61-f3fe129050a6.png)

Some properties like `color: f42`, and `justify-content: flex-start` are repeating, consider grouping these and other repeating properties together.

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-05-06 07:59 UTC, merged